<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Prodi extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        chek_session();
        $this->load->model('Prodi_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $prodi = $this->Prodi_model->get_all();

        $data = array(
            'prodi_data' => $prodi
        );

        $this->template->load('template','prodi_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Prodi_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'program_studi' => $row->program_studi,
	    );
            $this->template->load('template','prodi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('prodi'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('prodi/create_action'),
	    'id' => set_value('id'),
	    'program_studi' => set_value('program_studi'),
	);
        $this->template->load('template','prodi_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'program_studi' => $this->input->post('program_studi',TRUE),
	    );

            $this->Prodi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('prodi'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Prodi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('prodi/update_action'),
		'id' => set_value('id', $row->id),
		'program_studi' => set_value('program_studi', $row->program_studi),
	    );
            $this->template->load('template','prodi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('prodi'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'program_studi' => $this->input->post('program_studi',TRUE),
	    );

            $this->Prodi_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('prodi'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Prodi_model->get_by_id($id);

        if ($row) {
            $this->Prodi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('prodi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('prodi'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('program_studi', 'program studi', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Prodi.php */
/* Location: ./application/controllers/Prodi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-06 09:22:48 */
/* http://harviacode.com */